### PR TITLE
Add github action to autoformat code

### PR DESCRIPTION
**Pull request by mattsmithtaiko**
This will not run until a file in src is changed. I'll force a change in a follow-up PR to run the formatter on everything.

### CODE REVIEW

**Comment by mattsmithtaiko** [comment]
This is based on https://mskelton.medium.com/auto-formatting-code-using-prettier-and-github-actions-ed458f58b7df.

**Comment by isaac-looker** [comment]
wondering if we should each use a pre-commit hook to format. It would reduce the commit log, and avoid hiding descriptive commit messages on each line.

**Comment by mattsmithtaiko** [comment]
Some interesting comments on the choice between pre-commit hooks and running it in the CI here: https://www.reddit.com/r/ExperiencedDevs/comments/144fcqo/what_are_your_precommit_hooks/

There are differing opinions, but a few folks suggest doing it both in CI for all files (like here) as well as in a pre-commit hook for just staged files as a convenience for the developer.

What do you think?

**Comment by isaac-looker** [comment]
I agree that pre-commit hooks are not ideal. I think pre-save hooks at the editor level are best. I'm willing to try the GH action method.

**Comment by mattsmithtaiko** [comment]
Sounds good. There is already a `.prettierrc.json` file in the repo which we should be able to use with the VSCode Prettier extension for consistent code formatting.

**Review by isaac-looker — APPROVED** [review]

**Pull request merged**
