### PR TITLE
Mattcs frontend

### LINKED ISSUE #13: Access the landing page
- [ ]  Requirement 1: Landing page has a top navigation bar with the following menu items: ‘About’, ‘ Resources’, ‘Contact’
- [ ] Requirement 2: Landing page has entry points to three different sections: Data, Narratives, Research
- [ ] Requirement 3: Landing page has an inspirational hero image or video reflecting Black women in STEM

### PR DESCRIPTION
**Pull request by mattsmithtaiko**
This merges in the nearly-finished homepage matching the Figma mocks. It also adds `vue-router` to handle url navigation. Existing pages may not be directly reachable after this PR is merged without adding a route for them. Feel free to add needed routes for testing or otherwise in follow-up PRs.

Note the frontend is not perfect - there are still some CSS imperfections that should be fixed later. But I think this is good enough to merge and to start wiring up to the other pages.

Pull branch `mattcs-frontend` down to your machine to see changes.

Closes #13

### CODE REVIEW

**Review by isaac-looker — CHANGES_REQUESTED** [review]
`Read their stories` images seem to be transformed in the y-axis.

**Comment by isaac-looker** [comment]
Is there a plan for factoring out all common CSS into a global set of classes for re-using?

**Comment by mattsmithtaiko** [comment]
> `Read their stories` images seem to be transformed in the y-axis.

Yes, this is one of the things to be fixed. I figure it makes the most sense to pre-crop the image before adding it to our repo. It just needs to be square. It seems inefficient to load a bigger image and then crop it via CSS.

Since these are just placeholder images I didn't bother doing the cropping myself.

If we want it for an upcoming demo though I can crop it in GIMP and upload them.

**Comment by mattsmithtaiko** [comment]
> Is there a plan for factoring out all common CSS into a global set of classes for re-using?

I don't have a plan but I have been moving classes to a global css file (currently named `homepage.css`) as it makes sense. There is definitely a lot of cleanup that can be done CSS-wise. For example, some divs use class for styling while others use id. I figured we could do this cleanup in a second pass.

**Comment by mattsmithtaiko** [comment]
Created #76 and #77 to track some of the cleanup.

**Review by cernst122 — APPROVED** [review]

**Review by isaac-looker — APPROVED** [review]

**Pull request merged**
