### PR TITLE
Mattcs nsf23306 6 2

### LINKED ISSUE #160: Vue component for table #4
https://github.com/Spelman-College/spelman-dashboard/tree/main/frontend/src/data/nsf23306_6_2

### PR DESCRIPTION
**Pull request by mattsmithtaiko**
Create UI files for the nsf23306_6_2 dataset.

Closes #160.

### CODE REVIEW

**Review by isaac-looker — DISMISSED** [review]
When I compare the plot by race/ethnicity I only get 4 bars per year but I expect 8.

**Comment by mattsmithtaiko** [comment]
> When I compare the plot by race/ethnicity I only get 4 bars per year but I expect 8.
> 
> 

There are now the expected 7 ethnicities listed in the DCIDs:
image

Unit tests are now passing also.

**Comment by isaac-looker** [comment]
We may need to review how this dataset if formatted. See [here](https://ncses.nsf.gov/surveys/national-survey-college-graduates/2021#data) cc @amiersmith I think S&E Occupations are summary statistics for each occupation.
[nsf23306-tab006-002.pdf](https://github.com/Spelman-College/spelman-dashboard/files/12629415/nsf23306-tab006-002.pdf) We'll have to consider how to render between each of the summary categories for occupation, it seems.

**Review by isaac-looker — CHANGES_REQUESTED** [review]
See my comment on the conversation page. We may need to move the summary statistics or remove them.

**Comment by mattsmithtaiko** [comment]
I see... have you handled this in other data sets? Do we currently have a way to handle summary statistics? If not I think just remove them since users can get the same data by selecting the checkboxes for each of the subsets.

**Comment by isaac-looker** [comment]
After reviewing the source dataset, what seemed to be summary stats for occupation, turns out to be included in the total for each level of gender and race/ethnicity. So we should be good to merge this. 

example

**Review by isaac-looker — APPROVED** [review]

**Comment by mattsmithtaiko** [comment]
After discussion, I've commented out the ScienceAndEngineeringOccupation summary stat to unblock this PR and created #238 to track adding support for summary stats.

**Pull request merged**
